# JVM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android
android.useAndroidX=true
android.enableJetifier=false

# Kotlin
kotlin.code.style=official

# Necesario para KSP con AGP 9.x
android.disallowKotlinSourceSets=false

# Performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true